import json
import logging
import re
import requests
from odoo import api, fields, models, _
from collections import defaultdict


_logger = logging.getLogger(__name__)

class PartnerCreatoContainer(models.Model):
    _name = "partner.create.container"

    name = fields.Char(string=_("Name"))
    connector_ids = fields.One2many("partner.create.connector", "container_id", string=_("Connectors"))

class PartnerCreateConnector(models.Model):
    _name = "partner.create.connector"
    _description = "Partner Create from API"

    container_id = fields.Many2one("partner.create.container", help=_("Correlation with partner.create.container"))
    name = fields.Char(string=_("Name"))
    model = fields.Char(string=_("Model"))
    endpoint = fields.Char(string=_("Endpoint"))
    method = fields.Selection(selection=[("get", _("Get")), ("post", _("Post")),
                                         ("delete", _("Delete")), ("put", _("Update"))])
    timeout = fields.Integer(string=_("Timeout"), help=_("Timeout in seconds until the request stops waiting response"))
    header_ids = fields.One2many("partner.create.header", "partner_create_id", string=_("Headers"))
    body_ids = fields.One2many("partner.create.body", "partner_create_id", string=_("Body Elements"))
    mapping_ids = fields.One2many("partner.create.mapping", "partner_create_id", string=_("API Mappings"),
                                  help=_("Mappings generated by the API response to correlate with Odoo fields"))
    is_active = fields.Boolean(string=_("Active"))

    @property
    def _headers(self):
        self.ensure_one()
        return self.header_ids and {rec.key: rec.value for rec in self.header_ids} or {}

    def serialize_body(self):
        pass

    @staticmethod
    def parse_and_merge_dict(data, new_keys):
        results = []
        for item in data:
            merged_item = {}
            for key, value in item.items():
                if isinstance(value, dict):
                    merged_item.update({new_keys.get(key, key): v for k, v in value.items()})
                else:
                    if new_keys.get(key, key):
                        merged_item[new_keys.get(key, key)] = value or ""
            results.append(merged_item)
        return list(filter(None, results))

    @staticmethod
    def merge_sublevels(data):
        result = {}

        def merge_helper(data, prefix=""):
            if isinstance(data, dict):
                for key, value in data.items():
                    new_key = prefix + key
                    if isinstance(value, (dict, list)):
                        merge_helper(value, new_key + ".")
                    else:
                        result[new_key] = value
            elif isinstance(data, list):
                for i, item in enumerate(data):
                    merge_helper(item, prefix + f"[{i}].")

        merge_helper(data)
        return result

    @staticmethod
    def parse_and_create_unique_dict(data):
        result = {}
        counter = 0

        def process_key(key):
            nonlocal counter
            if "." in key:
                parent_key, subkey = key.split(".", 1)
                if parent_key in result:
                    new_key = process_key(subkey)
                    return f"{parent_key}.{new_key}"
                else:
                    return process_key(subkey)
            else:
                key_parts = key.split("[")
                if len(key_parts) > 1:
                    base_key = key_parts[0].rstrip(".")
                    if base_key in result:
                        counter += 1
                        return f"{base_key}_{counter}"
                    else:
                        return base_key
                else:
                    return key

        for key, value in data.items():
            new_key = process_key(key.strip())
            result[new_key] = value

        return result

    @staticmethod
    def group_and_normalize_dicts(data):
        result = defaultdict(dict)
        for key, value in data.items():
            if "." in key:
                new_key = f"{key.split('.')[0]}"
                last_key = f"{key.split('.')[-1]}"
                result[new_key][last_key] = value
            else:
                result[0][key] = value
        return list(result.values())

    def make_request(self, partner=None, data=None):
        if data is None:
            data = {}
        if partner is None:
            partner = self.env["res.partner"].search([("vat", "!=", False)], limit=1)
        endpoint = f"{self.endpoint}".replace("{vat}", re.sub(r'([^0-9]+)', '', partner.vat))
        res = getattr(requests, self.method)(endpoint, json=data, headers=self._headers, timeout=self.timeout)
        _logger.info(f"{res.content}")
        if res.status_code > 400:
            return {"warning": {"message": res.content}}
        content = json.loads(res.content)
        if isinstance(content, list):
            error = ";".join(filter(None, [cnt.get("error", {}).get("description", "") for cnt in content]))
        else:
            error = content.get("error", {}).get("description")
        if error:
            return {"warning": {"message": error}}
        else:
            content = self.merge_sublevels(content)
            if not self.mapping_ids:
                return self.parse_and_create_unique_dict(content)
            compat_with_odoo_fields = {m.api_key: m.odoo_key if m.odoo_key is not False else "" for m in
                                       self.mapping_ids}
            normalized_dict_list = self.group_and_normalize_dicts(content)
            content = self.parse_and_merge_dict(normalized_dict_list, compat_with_odoo_fields)

            def _m2o_search_helper(mp, cnt_dict):
                m2o_id = self.env[mp.model_to_search].search([("name", "=", cnt_dict.get(mp.odoo_key))], limit=1).id
                cnt_dict[mp.odoo_key] = m2o_id

            for mapping in self.mapping_ids:
                if mapping.m2o_force_search:
                    if isinstance(content, list):
                        for cnt in content:
                            _m2o_search_helper(mapping, cnt)
                    else:
                        _m2o_search_helper(mapping, content)

        if self.model and hasattr(partner, self.model):
            getattr(partner, self.model).unlink()
            setattr(partner, self.model, [(0, 0, data) for data in content])
        else:
            partner.with_context(skip_ro_vat_change=True).write(content[0])
        _logger.info(f"{content}")
        return content

    def prefetch_mapping_data(self):
        if not self.mapping_ids:
            vat_partner = self.env["res.partner"].search([("vat", "!=", False)], limit=1)
            self.mapping_ids = [(0, 0, {
                "api_key": k,
                "odoo_key": ""
            }) for k, _ in self.make_request(partner=vat_partner).items()]


class PartnerCreateMapping(models.Model):
    _name = "partner.create.mapping"
    _description = "Partner Create API Mapping"

    partner_create_id = fields.Many2one("partner.create.connector", help=_("Correlation with partner.create.connector"))
    api_key = fields.Char(string=_("API Key"))
    odoo_key = fields.Char(string=_("Odoo Key"))
    m2o_force_search = fields.Boolean(string=_("Force search"), help=_("Force search for M2O fields"))
    model_to_search = fields.Char(string=_("Model to search"))


class PartnerCreateHeader(models.Model):
    _name = "partner.create.header"
    _description = "Partner Create API Header"

    partner_create_id = fields.Many2one("partner.create.connector", help=_("Correlation with partner.create.connector"))
    key = fields.Char(string=_("Key"))
    value = fields.Char(string=_("Value"))


class PartnerCreateBody(models.Model):
    _name = "partner.create.body"
    _description = "Partner Create API Body"

    # TODO: implement logic for body mappings when request type is POST
    partner_create_id = fields.Many2one("partner.create.connector", help=_("Correlation with partner.create.connector"))
